DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(AUTHORID LONG AUTO_INCREMENT PRIMARY KEY, SURNAME VARCHAR(255), NAME VARCHAR(255));
DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(GENREID LONG AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255));
DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(BOOKID LONG AUTO_INCREMENT PRIMARY KEY, AUTHORID LONG, GENREID LONG, NAME VARCHAR(255));
